### PR TITLE
Add MMT to catalog

### PR DESCRIPTION
**Pull request by mreese84**

### CODE REVIEW

**Comment by mreese84** [comment]
@vjphilli opened the PR for adding MMT to the catalog, but we have not yet pushed our code to the new NASA repo. I just wanted to get this up for when we are ready (which should be today or Monday.)

**Comment by vjphilli** [comment]
Thanks for the heads up @mreese84! I will await your code!

**Comment by mreese84** [comment]
@vjphilli, MMT code is now up at https://github.com/nasa/mmt

**Comment by vjphilli** [comment]
Could you write up the JSON metadata record for your code, so that I can merge it into the catalog? Thanks!

**Comment by mreese84** [comment]
@vjphilli, it's there. However, it looks like my editor took some liberties in "cleaning up" the formatting of catalog.json. You can see the added metadata here: https://github.com/nasa/Open-Source-Catalog/pull/36/files#diff-afeac58a78a5123382ab0560a96b630bR6804 (it may take a few seconds to load).

If accepted, this PR would add the MMT record and also clean up the formatting making things more consistent throughout the catalog.json file. If that's no good for you I can take a step back and see if I can configure my editor to "ignore" the formatting issues. Thoughts?

**Comment by vjphilli** [comment]
Add mmt metadata record to the catalog

**Pull request closed without merging**
